### ISSUE TITLE
Mod Recommendations - GOG and Dungeon Mobs

### ISSUE THREAD

**Issue by RieLize** [Heaveness/RotN-BPG-Edition#4]
Hey this is Brizen from discord,
Wanted to recommend Grimoire of Gaia (or Grimoire of Gaia Redux for anime reduction) and Dungeon Mobs as potential mods for this fork. They add mob variety and are supported by AW2 so it would also add new AW2 structures to house these new mobs.

**Comment by Heaveness** [comment]
GoG has already been planned and added into BPG 1.1 update which is currently in closed beta testing. Dungeon Mobs, maybe but right now base RotN and BPG already have a lot of mob variety. Might consider in the future.
