### ISSUE TITLE
Getting revived in the aether dimension causes you to revive at your set spawn point

### ISSUE THREAD

**Issue by RieLize** [Heaveness/RotN-BPG-Edition#6]
title

**Comment by Heaveness** [comment]
This is a known issue within Hardcore Revival mod. There isn't a fix for this sadly... You will have to put this issue up to the mod dev themselves. Only way around it is for you to set the world spawn at your base.

**Comment by RieLize** [comment]
Ah ok. Yeah, we'd get revived at our bed in base so it's not that big of an issue, just a minor inconvenience.
